export type Quote = {
  text: string;
  author?: string;
};

export const quotes: Quote[] = [
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "I am no bird; and no net ensnares me: I am a free human being with an independent will.", author: "Charlotte Brontë" },
  { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { text: "The most courageous act is still to think for yourself. Aloud.", author: "Coco Chanel" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { text: "I care for myself. The more solitary, the more friendless, the more unsustained I am, the more I will respect myself.", author: "Charlotte Brontë" },
  { text: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe" },
  { text: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", author: "Rumi" },
  { text: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein" },
  { text: "When I discover who I am, I'll be free.", author: "Ralph Ellison" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "I'd rather die my way than live yours.", author: "Lauren Oliver" },
  { text: "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", author: "Neil Gaiman" },
  { text: "Freedom: to ask nothing, to expect nothing, to depend on nothing.", author: "Ayn Rand" },
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane" },
  { text: "I am not an angel; and I will not be one till I die: I will be myself.", author: "Charlotte Brontë" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
  { text: "The greatest thing in the world is to know how to belong to oneself.", author: "Michel de Montaigne" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "To find yourself, think for yourself.", author: "Socrates" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "I do not wish them to have power over men; but over themselves.", author: "Mary Wollstonecraft" },
  { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { text: "Marriage is a fine institution, but I'm not ready for an institution.", author: "Mae West" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "If you truly want to be respected by people you love, you must prove to them that you can survive without them.", author: "Michael Bassey Johnson" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston S. Churchill" },
  { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs" },
  { text: "And, when you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho" },
  { text: "So the fact that I'm me and no one else is one of my greatest assets. Emotional hurt is the price a person has to pay in order to be independent.", author: "Haruki Murakami" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn" },
  { text: "People have only as much liberty as they have the intelligence to want and the courage to take.", author: "Emma Goldman" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama XIV" },
  { text: "I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.", author: "Marilyn Monroe" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Be that strong girl that everyone knew would make it through the worst, be that fearless girl, the one who would dare to do anything, be that independent girl who didn't need a man; be that girl who never backed down.", author: "Taylor Swift" },
  { text: "Pain is inevitable. Suffering is optional.", author: "Haruki Murakami" },
  { text: "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", author: "Martin Luther King Jr." },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
  { text: "If you want to be happy, be.", author: "Leo Tolstoy" },
  { text: "It is better to be hated for what you are than to be loved for what you are not.", author: "André Gide" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "The past has no power over the present moment.", author: "Eckhart Tolle" },
  { text: "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", author: "Friedrich Nietzsche" },
  { text: "Though nobody can go back and make a new beginning, anyone can start over and make a new ending.", author: "Chico Xavier" },
  { text: "The opposite of love is not hate, it's indifference.", author: "Elie Wiesel" },
  { text: "Always do what you are afraid to do.", author: "Ralph Waldo Emerson" },
  { text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu" },
  { text: "Happiness is only real when shared.", author: "Jon Krakauer" },
  { text: "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.", author: "Sarah Dessen" },
  { text: "Life is a shipwreck, but we must not forget to sing in the lifeboats.", author: "Voltaire" },
  { text: "Love is that condition in which the happiness of another person is essential to your own.", author: "Robert A. Heinlein" },
  { text: "A ship is safe in harbor, but that's not what ships are for.", author: "John A. Shedd" },
  { text: "Have you ever been in love? Horrible, isn't it? It makes you so vulnerable. It opens your chest and it opens up your heart and it means that someone can get inside you and mess you up.", author: "Neil Gaiman" },
  { text: "You were born with wings, why prefer to crawl through life?", author: "Rumi" },
  { text: "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.", author: "Jane Austen" },
  { text: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", author: "Roy T. Bennett" },
  { text: "Love is like the wind, you can't see it but you can feel it.", author: "Nicholas Sparks" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { text: "You don't love someone because they're perfect, you love them in spite of the fact that they're not.", author: "Jodi Picoult" },
  { text: "The higher we soar the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche" },
  { text: "Love never dies a natural death. It dies because we don't know how to replenish its source.", author: "Anaïs Nin" },
  { text: "If you don't go after what you want, you'll never have it. If you don't ask, the answer is always no. If you don't step forward, you're always in the same place.", author: "Nora Roberts" },
  { text: "If I had a flower for every time I thought of you... I could walk through my garden forever.", author: "Alfred Tennyson" },
  { text: "Talent hits a target no one else can hit. Genius hits a target no one else can see.", author: "Arthur Schopenhauer" },
  { text: "We're all a little weird. And life is a little weird. And when we find someone whose weirdness is compatible with ours, we join up with them and fall into mutually satisfying weirdness — and call it love — true love.", author: "Robert Fulghum" },
  { text: "What's the good of living if you don't try a few things?", author: "Charles M. Schulz" },
  { text: "I am nothing special — a common man with common thoughts who has led a common life. But I've loved another with all my heart and soul, and to me this has always been enough.", author: "Nicholas Sparks" },
  { text: "May you live every day of your life.", author: "Jonathan Swift" },
  { text: "How wrong is it for a woman to expect the man to build the world she wants, rather than to create it herself?", author: "Anaïs Nin" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "Be mindful. Be grateful. Be positive. Be true. Be kind.", author: "Roy T. Bennett" },
  { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
  { text: "Hell is empty and all the devils are here.", author: "William Shakespeare" },
  { text: "One love, one heart, one destiny.", author: "Bob Marley" },
  { text: "None but ourselves can free our minds.", author: "Bob Marley" },
  { text: "If you're reading this — congratulations, you're alive. If that's not something to smile about, then I don't know what is.", author: "Chad Sugg" },
  { text: "The most beautiful things in the world cannot be seen or touched, they are felt with the heart.", author: "Antoine de Saint-Exupéry" },
  { text: "Live in the present, remember the past, and fear not the future, for it doesn't exist and never shall. There is only now.", author: "Christopher Paolini" },
  { text: "I will not be famous, I will not be great. I will go on adventuring, changing, opening my mind and my eyes, refusing to be stamped and stereotyped.", author: "Virginia Woolf" },
  { text: "You love me. Real or not real? — I tell him, Real.", author: "Suzanne Collins" },
  { text: "I'm single because I was born that way.", author: "Mae West" },
];
